/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/about/about" |
       "/pages/functionDesk/index" |
       "/pages/login/index" |
       "/pages/my/index" |
       "/pages/otherPages/EducationSys/index" |
       "/pages/otherPages/SelectClassSys/index" |
       "/pages/otherPages/SmartPlatform/index" |
       "/pages/otherPages/baseService/view/bookSelect" |
       "/pages/otherPages/baseService/view/classRoomApplication" |
       "/pages/otherPages/baseService/view/oneCardTo" |
       "/pages/otherPages/baseService/view/patentApplication" |
       "/pages/otherPages/commonUse/views/myClassExcel" |
       "/pages/otherPages/commonUse/views/myHomework" |
       "/pages/otherPages/commonUse/views/qualiyAssessment" |
       "/pages/otherPages/commonUse/views/scanToSign" |
       "/pages/otherPages/operateSys/views/financialPay" |
       "/pages/otherPages/operateSys/views/laboratoryManage" |
       "/pages/otherPages/SmartPlatform/views/inClassAssessment" |
       "/pages/otherPages/SmartPlatform/views/subView/finishedExam" |
       "/pages/otherPages/SmartPlatform/views/subView/startExam";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/functionDesk/index" | "/pages/my/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
